// Mock roadmap data service
// In a real application, this would fetch from an API

const roadmapData = {
    'software-developer': {
        beginner: [
            {
                title: 'Programming Fundamentals',
                description: 'Master the core concepts of programming including variables, data types, control structures, and functions.',
                duration: '4-6 weeks',
                difficulty: 'Easy',
                tags: ['Python', 'JavaScript', 'Basics'],
                topics: [
                    'Variables and Data Types',
                    'Control Flow (if/else, loops)',
                    'Functions and Scope',
                    'Basic Data Structures (Arrays, Objects)',
                    'Debugging Techniques',
                ],
                progress: 0,
            },
            {
                title: 'Version Control with Git',
                description: 'Learn to track changes, collaborate with others, and manage code using Git and GitHub.',
                duration: '1-2 weeks',
                difficulty: 'Easy',
                tags: ['Git', 'GitHub', 'Collaboration'],
                topics: [
                    'Git Basics (init, add, commit)',
                    'Branching and Merging',
                    'Remote Repositories',
                    'Pull Requests',
                    'Conflict Resolution',
                ],
                progress: 0,
            },
            {
                title: 'Web Development Basics',
                description: 'Build foundational skills in HTML, CSS, and JavaScript to create interactive web pages.',
                duration: '6-8 weeks',
                difficulty: 'Easy',
                tags: ['HTML', 'CSS', 'JavaScript'],
                topics: [
                    'HTML Structure and Semantics',
                    'CSS Styling and Layouts',
                    'Flexbox and Grid',
                    'DOM Manipulation',
                    'Event Handling',
                    'Responsive Design',
                ],
                progress: 0,
            },
            {
                title: 'Introduction to Databases',
                description: 'Understand how to store, retrieve, and manage data using SQL and relational databases.',
                duration: '3-4 weeks',
                difficulty: 'Medium',
                tags: ['SQL', 'MySQL', 'PostgreSQL'],
                topics: [
                    'Database Concepts',
                    'SQL Queries (SELECT, INSERT, UPDATE, DELETE)',
                    'Joins and Relationships',
                    'Database Design',
                    'Indexing Basics',
                ],
                progress: 0,
            },
            {
                title: 'Build Your First Project',
                description: 'Apply your skills by building a complete web application from scratch.',
                duration: '2-4 weeks',
                difficulty: 'Medium',
                tags: ['Project', 'Full Stack', 'Portfolio'],
                topics: [
                    'Project Planning',
                    'Frontend Development',
                    'Backend Basics',
                    'Database Integration',
                    'Deployment',
                ],
                progress: 0,
            },
        ],
        intermediate: [
            {
                title: 'Advanced JavaScript & ES6+',
                description: 'Deep dive into modern JavaScript features and advanced programming patterns.',
                duration: '3-4 weeks',
                difficulty: 'Medium',
                tags: ['JavaScript', 'ES6+', 'Advanced'],
                topics: [
                    'Promises and Async/Await',
                    'Destructuring and Spread Operators',
                    'Classes and Modules',
                    'Closures and Prototypes',
                    'Error Handling',
                ],
                progress: 0,
            },
            {
                title: 'Frontend Frameworks (React)',
                description: 'Master React to build modern, component-based user interfaces.',
                duration: '6-8 weeks',
                difficulty: 'Medium',
                tags: ['React', 'JSX', 'Components'],
                topics: [
                    'React Components and Props',
                    'State Management',
                    'Hooks (useState, useEffect, etc.)',
                    'React Router',
                    'Performance Optimization',
                ],
                progress: 0,
            },
            {
                title: 'Backend Development with Node.js',
                description: 'Build robust server-side applications using Node.js and Express.',
                duration: '4-6 weeks',
                difficulty: 'Medium',
                tags: ['Node.js', 'Express', 'API'],
                topics: [
                    'Node.js Fundamentals',
                    'Express.js Framework',
                    'RESTful API Design',
                    'Authentication & Authorization',
                    'Error Handling & Logging',
                ],
                progress: 0,
            },
            {
                title: 'Testing & Quality Assurance',
                description: 'Learn to write tests and ensure code quality through automated testing.',
                duration: '2-3 weeks',
                difficulty: 'Medium',
                tags: ['Jest', 'Testing', 'TDD'],
                topics: [
                    'Unit Testing',
                    'Integration Testing',
                    'Test-Driven Development',
                    'Mocking and Stubbing',
                    'Code Coverage',
                ],
                progress: 0,
            },
            {
                title: 'DevOps Fundamentals',
                description: 'Understand CI/CD pipelines, containerization, and deployment strategies.',
                duration: '3-4 weeks',
                difficulty: 'Hard',
                tags: ['Docker', 'CI/CD', 'DevOps'],
                topics: [
                    'Docker Basics',
                    'Container Orchestration',
                    'CI/CD Pipelines',
                    'Cloud Deployment',
                    'Monitoring and Logging',
                ],
                progress: 0,
            },
        ],
        advanced: [
            {
                title: 'System Design & Architecture',
                description: 'Learn to design scalable, maintainable systems for large-scale applications.',
                duration: '4-6 weeks',
                difficulty: 'Hard',
                tags: ['Architecture', 'Scalability', 'Design'],
                topics: [
                    'Design Patterns',
                    'Microservices Architecture',
                    'Load Balancing',
                    'Caching Strategies',
                    'Database Sharding',
                ],
                progress: 0,
            },
            {
                title: 'Advanced Backend Patterns',
                description: 'Master advanced backend concepts including message queues, event-driven architecture, and distributed systems.',
                duration: '4-5 weeks',
                difficulty: 'Hard',
                tags: ['Kafka', 'Redis', 'Distributed'],
                topics: [
                    'Message Queues (RabbitMQ, Kafka)',
                    'Event-Driven Architecture',
                    'CQRS and Event Sourcing',
                    'Distributed Transactions',
                    'Service Mesh',
                ],
                progress: 0,
            },
            {
                title: 'Performance Optimization',
                description: 'Learn techniques to optimize application performance at every level.',
                duration: '3-4 weeks',
                difficulty: 'Hard',
                tags: ['Performance', 'Optimization', 'Profiling'],
                topics: [
                    'Profiling and Benchmarking',
                    'Database Optimization',
                    'Caching Layers',
                    'CDN Integration',
                    'Frontend Performance',
                ],
                progress: 0,
            },
            {
                title: 'Security Best Practices',
                description: 'Implement security measures to protect applications from common vulnerabilities.',
                duration: '3-4 weeks',
                difficulty: 'Hard',
                tags: ['Security', 'OWASP', 'Authentication'],
                topics: [
                    'OWASP Top 10',
                    'Secure Authentication',
                    'Encryption and Hashing',
                    'Security Auditing',
                    'Penetration Testing Basics',
                ],
                progress: 0,
            },
            {
                title: 'Leadership & Mentoring',
                description: 'Develop soft skills to lead teams and mentor junior developers.',
                duration: '2-3 weeks',
                difficulty: 'Medium',
                tags: ['Leadership', 'Mentoring', 'Communication'],
                topics: [
                    'Technical Leadership',
                    'Code Review Best Practices',
                    'Mentoring Techniques',
                    'Agile Methodologies',
                    'Team Collaboration',
                ],
                progress: 0,
            },
        ],
    },
    'data-scientist': {
        beginner: [
            {
                title: 'Python for Data Science',
                description: 'Learn Python programming with a focus on data manipulation and analysis.',
                duration: '4-6 weeks',
                difficulty: 'Easy',
                tags: ['Python', 'Pandas', 'NumPy'],
                topics: [
                    'Python Basics',
                    'NumPy for Numerical Computing',
                    'Pandas for Data Manipulation',
                    'Data Visualization with Matplotlib',
                    'Jupyter Notebooks',
                ],
                progress: 0,
            },
            {
                title: 'Statistics Fundamentals',
                description: 'Build a strong foundation in statistics for data analysis.',
                duration: '4-5 weeks',
                difficulty: 'Medium',
                tags: ['Statistics', 'Probability', 'Math'],
                topics: [
                    'Descriptive Statistics',
                    'Probability Theory',
                    'Hypothesis Testing',
                    'Correlation and Regression',
                    'Statistical Distributions',
                ],
                progress: 0,
            },
            {
                title: 'Data Visualization',
                description: 'Learn to create compelling visualizations to communicate insights.',
                duration: '2-3 weeks',
                difficulty: 'Easy',
                tags: ['Matplotlib', 'Seaborn', 'Visualization'],
                topics: [
                    'Chart Types and Use Cases',
                    'Matplotlib Customization',
                    'Seaborn for Statistical Plots',
                    'Interactive Visualizations',
                    'Dashboard Design Principles',
                ],
                progress: 0,
            },
            {
                title: 'SQL for Data Analysis',
                description: 'Query and analyze data using SQL.',
                duration: '2-3 weeks',
                difficulty: 'Easy',
                tags: ['SQL', 'Database', 'Queries'],
                topics: [
                    'Basic SQL Queries',
                    'Aggregations and Grouping',
                    'Joins and Subqueries',
                    'Window Functions',
                    'Data Extraction Techniques',
                ],
                progress: 0,
            },
        ],
        intermediate: [
            {
                title: 'Machine Learning Fundamentals',
                description: 'Understand core ML algorithms and how to apply them.',
                duration: '6-8 weeks',
                difficulty: 'Medium',
                tags: ['ML', 'Scikit-learn', 'Algorithms'],
                topics: [
                    'Supervised Learning',
                    'Unsupervised Learning',
                    'Model Evaluation',
                    'Feature Engineering',
                    'Hyperparameter Tuning',
                ],
                progress: 0,
            },
            {
                title: 'Deep Learning Basics',
                description: 'Introduction to neural networks and deep learning.',
                duration: '4-6 weeks',
                difficulty: 'Hard',
                tags: ['TensorFlow', 'Keras', 'Neural Networks'],
                topics: [
                    'Neural Network Architecture',
                    'Backpropagation',
                    'CNNs for Image Data',
                    'RNNs for Sequential Data',
                    'Transfer Learning',
                ],
                progress: 0,
            },
            {
                title: 'Big Data Technologies',
                description: 'Work with large-scale data using distributed computing.',
                duration: '3-4 weeks',
                difficulty: 'Medium',
                tags: ['Spark', 'Hadoop', 'Big Data'],
                topics: [
                    'Introduction to Big Data',
                    'Apache Spark',
                    'Distributed Computing Concepts',
                    'Data Pipelines',
                    'Cloud Data Platforms',
                ],
                progress: 0,
            },
        ],
        advanced: [
            {
                title: 'Advanced Deep Learning',
                description: 'Master advanced neural network architectures and techniques.',
                duration: '6-8 weeks',
                difficulty: 'Hard',
                tags: ['Transformers', 'GANs', 'Advanced ML'],
                topics: [
                    'Transformers and Attention',
                    'Generative Models (GANs, VAEs)',
                    'Reinforcement Learning',
                    'Natural Language Processing',
                    'Computer Vision Advanced',
                ],
                progress: 0,
            },
            {
                title: 'MLOps & Model Deployment',
                description: 'Deploy and manage ML models in production.',
                duration: '4-5 weeks',
                difficulty: 'Hard',
                tags: ['MLOps', 'Deployment', 'Production'],
                topics: [
                    'Model Serving',
                    'Pipeline Automation',
                    'Model Monitoring',
                    'A/B Testing',
                    'Feature Stores',
                ],
                progress: 0,
            },
            {
                title: 'Research & Innovation',
                description: 'Stay current with latest research and contribute to the field.',
                duration: '3-4 weeks',
                difficulty: 'Hard',
                tags: ['Research', 'Papers', 'Innovation'],
                topics: [
                    'Reading Research Papers',
                    'Reproducing Experiments',
                    'Contributing to Open Source',
                    'Publishing Results',
                    'Academic Collaboration',
                ],
                progress: 0,
            },
        ],
    },
    'ui-ux-designer': {
        beginner: [
            {
                title: 'Design Foundations',
                description: 'Learn the core principles of visual design.',
                duration: '3-4 weeks',
                difficulty: 'Easy',
                tags: ['Design', 'Principles', 'Basics'],
                topics: [
                    'Color Theory',
                    'Typography',
                    'Layout and Composition',
                    'Visual Hierarchy',
                    'Design Systems',
                ],
                progress: 0,
            },
            {
                title: 'User Experience Basics',
                description: 'Understand UX principles and user-centered design.',
                duration: '3-4 weeks',
                difficulty: 'Easy',
                tags: ['UX', 'User Research', 'Design Thinking'],
                topics: [
                    'What is UX?',
                    'User Research Methods',
                    'Personas and User Journeys',
                    'Information Architecture',
                    'Accessibility Basics',
                ],
                progress: 0,
            },
            {
                title: 'Design Tools (Figma)',
                description: 'Master Figma for creating stunning designs.',
                duration: '2-3 weeks',
                difficulty: 'Easy',
                tags: ['Figma', 'Tools', 'Prototyping'],
                topics: [
                    'Figma Interface',
                    'Components and Variants',
                    'Auto Layout',
                    'Prototyping',
                    'Collaboration Features',
                ],
                progress: 0,
            },
        ],
        intermediate: [
            {
                title: 'Advanced Prototyping',
                description: 'Create interactive prototypes for user testing.',
                duration: '2-3 weeks',
                difficulty: 'Medium',
                tags: ['Prototyping', 'Figma', 'Interactions'],
                topics: [
                    'Micro-interactions',
                    'Animation Principles',
                    'Advanced Figma Prototyping',
                    'Usability Testing',
                    'Prototype Documentation',
                ],
                progress: 0,
            },
            {
                title: 'Design Systems',
                description: 'Build and maintain scalable design systems.',
                duration: '4-5 weeks',
                difficulty: 'Medium',
                tags: ['Design Systems', 'Components', 'Tokens'],
                topics: [
                    'Component Libraries',
                    'Design Tokens',
                    'Documentation',
                    'Version Control for Design',
                    'Cross-team Collaboration',
                ],
                progress: 0,
            },
        ],
        advanced: [
            {
                title: 'UX Strategy',
                description: 'Learn to align design with business goals.',
                duration: '3-4 weeks',
                difficulty: 'Hard',
                tags: ['Strategy', 'Business', 'Leadership'],
                topics: [
                    'Business Understanding',
                    'Metrics and KPIs',
                    'Stakeholder Management',
                    'Design Leadership',
                    'Product Strategy',
                ],
                progress: 0,
            },
            {
                title: 'Advanced Research Methods',
                description: 'Master qualitative and quantitative research techniques.',
                duration: '3-4 weeks',
                difficulty: 'Hard',
                tags: ['Research', 'Analytics', 'Testing'],
                topics: [
                    'Advanced User Testing',
                    'Analytics Deep Dive',
                    'A/B Testing',
                    'Survey Design',
                    'Research Synthesis',
                ],
                progress: 0,
            },
        ],
    },
};

// Default roadmap for roles that don't have specific data
const defaultRoadmap = {
    beginner: [
        {
            title: 'Foundation Skills',
            description: 'Build the essential skills needed for this career path.',
            duration: '4-6 weeks',
            difficulty: 'Easy',
            tags: ['Basics', 'Fundamentals'],
            topics: [
                'Core Concepts',
                'Industry Tools',
                'Best Practices',
                'Communication Skills',
            ],
            progress: 0,
        },
        {
            title: 'Practical Application',
            description: 'Apply your knowledge through hands-on projects.',
            duration: '4-6 weeks',
            difficulty: 'Medium',
            tags: ['Projects', 'Practice'],
            topics: [
                'Project Planning',
                'Implementation',
                'Problem Solving',
                'Documentation',
            ],
            progress: 0,
        },
    ],
    intermediate: [
        {
            title: 'Advanced Techniques',
            description: 'Deepen your expertise with advanced concepts.',
            duration: '6-8 weeks',
            difficulty: 'Medium',
            tags: ['Advanced', 'Techniques'],
            topics: [
                'Advanced Concepts',
                'Industry Standards',
                'Performance Optimization',
                'Collaboration',
            ],
            progress: 0,
        },
        {
            title: 'Specialization',
            description: 'Focus on specific areas of expertise.',
            duration: '4-6 weeks',
            difficulty: 'Hard',
            tags: ['Specialization', 'Expertise'],
            topics: [
                'Choose Your Path',
                'Deep Dive',
                'Certifications',
                'Portfolio Building',
            ],
            progress: 0,
        },
    ],
    advanced: [
        {
            title: 'Leadership & Strategy',
            description: 'Develop leadership skills and strategic thinking.',
            duration: '4-6 weeks',
            difficulty: 'Hard',
            tags: ['Leadership', 'Strategy'],
            topics: [
                'Technical Leadership',
                'Team Management',
                'Strategic Planning',
                'Mentoring',
            ],
            progress: 0,
        },
        {
            title: 'Innovation & Research',
            description: 'Stay ahead with cutting-edge knowledge and innovation.',
            duration: '4-6 weeks',
            difficulty: 'Hard',
            tags: ['Innovation', 'Research'],
            topics: [
                'Industry Trends',
                'Research Methods',
                'Innovation Practices',
                'Thought Leadership',
            ],
            progress: 0,
        },
    ],
};

export const getRoadmap = (role, skillLevel) => {
    const roleData = roadmapData[role] || defaultRoadmap;
    return roleData[skillLevel] || roleData.beginner;
};

export const getRoleName = (roleValue) => {
    const roleNames = {
        'software-developer': 'Software Developer',
        'data-scientist': 'Data Scientist',
        'ui-ux-designer': 'UI/UX Designer',
        'devops-engineer': 'DevOps Engineer',
        'cybersecurity': 'Cybersecurity Specialist',
        'ml-engineer': 'ML Engineer',
        'mobile-developer': 'Mobile Developer',
        'database-admin': 'Database Administrator',
    };
    return roleNames[roleValue] || roleValue;
};

export const getSkillLevelName = (levelValue) => {
    const levelNames = {
        beginner: 'Beginner',
        intermediate: 'Intermediate',
        advanced: 'Advanced',
    };
    return levelNames[levelValue] || levelValue;
};
